#!/bin/bash
if  [ -e /etc/ httpd}; then comment here
exit 0 ;                         
 fi                              
 yum -y install httpd mod-ssl    
 systemctl start httpd            
 sed -i 's/^/#/g' / etc/httpd/conf.d/welcome.conf      
 echo "<html><h1>Hi there NTI 300</h1><body></html>"/var/www/html/index/html   
systemctl restart httpd         #restart apache so the changes take effect
